export const TOGGLE_MODAL = 'TOGGLE_MODAL'

export const ADD_WORKS_VISIBILITY_FILTER = 'ADD_WORKS_VISIBILITY_FILTER'
export const REMOVE_WORKS_FILTER = 'REMOVE_WORKS_VISIBILITY_FILTER'
export const TOGGLE_WORKS_VISIBILITY_FILTERS = 'TOGGLE_WORKS_VISIBILITY_FILTERS'
