export const PROFESSIONAL = 'professional'
export const OPEN_SOURCE = 'open_source'
export const CONTRACT = 'contract'
export const JAVASCRIPT = 'javascript'
export const PYTHON = 'python'
export const JAVA = 'java'
export const BASH = 'bash'
